# Site settings
main: "YUN DAE HEE"
title: 076923
email: 076923@naver.com
lang: "ko"
description: >
 C#, Python, Arduino, OpenCV, CAD 등을 다루며 연구, 개발 등에 필요한 정보를 공유하고 나누기 위한 목적입니다.
baseurl: ""
url: "https://076923.github.io/"
favicon: 'favicon.ico'

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title

jekyll-theme-simple-blog:
  date_format: "%Y-%M-%d"

theme: # leave it empty

header_page_refs: ['coding','posts','about']

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

show_post_image_posts_list: false

header:
  image: /assets/patterns/symphony.png

# social
author:
  name: "윤대희"
  picture: assets/img/profile-60.png

image: /assets/img/profile-225.png

# gitlab on site
gitlab:
  owner_url: https://gitlab.com/076923

# github on site
github:
  owner_url: https://github.com/076923

variable:
  read-per-minute: 35
  reading: "읽는 데"
  read-time: "분"

disqus: https-076923-github-io
github_username: 076923
disqus_username: yundaehee